const dataOfKeys = [
  {
    code: 'Backquote',
    unit: 'symbol',
    en: ['`', '~'],
    ru: ['ё', 'Ё'],
  },
  {
    code: 'Digit1',
    unit: 'digit',
    en: ['1', '!'],
    ru: ['1', '!'],
  },
  {
    code: 'Digit2',
    unit: 'digit',
    en: ['2', '@'],
    ru: ['2', '"'],
  },
  {
    code: 'Digit3',
    unit: 'digit',
    en: ['3', '#'],
    ru: ['3', '№'],
  },
  {
    code: 'Digit4',
    unit: 'digit',
    en: ['4', '$'],
    ru: ['4', ';'],
  },
  {
    code: 'Digit5',
    unit: 'digit',
    en: ['5', '%'],
    ru: ['5', '%'],
  },
  {
    code: 'Digit6',
    unit: 'digit',
    en: ['6', '^'],
    ru: ['6', ':'],
  },
  {
    code: 'Digit7',
    unit: 'digit',
    en: ['7', '&'],
    ru: ['7', '?'],
  },
  {
    code: 'Digit8',
    unit: 'digit',
    en: ['8', '*'],
    ru: ['8', '*'],
  },
  {
    code: 'Digit9',
    unit: 'digit',
    en: ['9', '('],
    ru: ['9', '('],
  },
  {
    code: 'Digit0',
    unit: 'digit',
    en: ['0', ')'],
    ru: ['0', ')'],
  },
  {
    code: 'Minus',
    unit: 'symbol',
    en: ['-', '_'],
    ru: ['-', '_'],
  },
  {
    code: 'Equal',
    unit: 'symbol',
    en: ['=', '+'],
    ru: ['=', '+'],
  },
  {
    code: 'Delete',
    unit: 'spec',
    en: ['del'],
    ru: ['del'],
  },
  {
    code: 'Backspace',
    unit: 'spec',
    en: ['Backspace'],
    ru: ['Backspace'],
  },
  {
    code: 'Tab',
    unit: 'spec',
    en: ['Tab'],
    ru: ['Tab'],
  },
  {
    code: 'KeyQ',
    unit: 'symbol',
    en: ['q', 'Q'],
    ru: ['й', 'Й'],
  },
  {
    code: 'KeyW',
    unit: 'symbol',
    en: ['w', 'W'],
    ru: ['ц', 'Ц'],
  },
  {
    code: 'KeyE',
    unit: 'symbol',
    en: ['e', 'E'],
    ru: ['у', 'У'],
  },
  {
    code: 'KeyR',
    unit: 'symbol',
    en: ['r', 'R'],
    ru: ['к', 'K'],
  },
  {
    code: 'KeyT',
    unit: 'symbol',
    en: ['t', 'T'],
    ru: ['е', 'Е'],
  },
  {
    code: 'KeyY',
    unit: 'symbol',
    en: ['y', 'Y'],
    ru: ['н', 'Н'],
  },
  {
    code: 'KeyU',
    unit: 'symbol',
    en: ['u', 'U'],
    ru: ['г', 'Г'],
  },
  {
    code: 'KeyI',
    unit: 'symbol',
    en: ['i', 'I'],
    ru: ['ш', 'Ш'],
  },
  {
    code: 'KeyO',
    unit: 'symbol',
    en: ['o', 'O'],
    ru: ['щ', 'Щ'],
  },
  {
    code: 'KeyP',
    unit: 'symbol',
    en: ['p', 'P'],
    ru: ['з', 'З'],
  },
  {
    code: 'BracketLeft',
    unit: 'splitSymbol',
    en: ['[', '{'],
    ru: ['х', 'Х'],
  },
  {
    code: 'BracketRight',
    unit: 'splitSymbol',
    en: [']', '}'],
    ru: ['ъ', 'Ъ'],
  },
  {
    code: 'Backslash',
    unit: 'symbol',
    en: ['\\', '|'],
    ru: ['\\', '/'],
  },
  {
    code: 'CapsLock',
    unit: 'spec',
    en: ['CapsLock'],
    ru: ['CapsLock'],
  },
  {
    code: 'KeyA',
    unit: 'symbol',
    en: ['a', 'A'],
    ru: ['ф', 'Ф'],
  },
  {
    code: 'KeyS',
    unit: 'symbol',
    en: ['s', 'S'],
    ru: ['ы', 'Ы'],
  },
  {
    code: 'KeyD',
    unit: 'symbol',
    en: ['d', 'D'],
    ru: ['в', 'В'],
  },
  {
    code: 'KeyF',
    unit: 'symbol',
    en: ['f', 'F'],
    ru: ['а', 'А'],
  },
  {
    code: 'KeyG',
    unit: 'symbol',
    en: ['g', 'G'],
    ru: ['п', 'П'],
  },
  {
    code: 'KeyH',
    unit: 'symbol',
    en: ['h', 'H'],
    ru: ['р', 'Р'],
  },
  {
    code: 'KeyJ',
    unit: 'symbol',
    en: ['j', 'J'],
    ru: ['о', 'О'],
  },
  {
    code: 'KeyK',
    unit: 'symbol',
    en: ['k', 'K'],
    ru: ['л', 'Л'],
  },
  {
    code: 'KeyL',
    unit: 'symbol',
    en: ['l'],
    ru: ['д'],
  },
  {
    code: 'Semicolon',
    unit: 'splitSymbol',
    en: [';', ':'],
    ru: ['ж', 'Ж'],
  },
  {
    code: 'Quote',
    unit: 'splitSymbol',
    en: ["'", '"'],
    ru: ['э', 'Э'],
  },
  {
    code: 'Enter',
    unit: 'spec',
    en: ['Enter'],
    ru: ['Enter'],
  },
  {
    code: 'ShiftLeft',
    unit: 'spec',
    en: ['Shift'],
    ru: ['Shift'],
  },
  {
    code: 'KeyZ',
    unit: 'symbol',
    en: ['z', 'Z'],
    ru: ['я', 'Я'],
  },
  {
    code: 'KeyX',
    unit: 'symbol',
    en: ['x', 'X'],
    ru: ['ч', 'Ч'],
  },
  {
    code: 'KeyC',
    unit: 'symbol',
    en: ['c', 'C'],
    ru: ['с', 'С'],
  },
  {
    code: 'KeyV',
    unit: 'symbol',
    en: ['v', 'V'],
    ru: ['м', 'М'],
  },
  {
    code: 'KeyB',
    unit: 'symbol',
    en: ['b', 'B'],
    ru: ['и', 'И'],
  },
  {
    code: 'KeyN',
    unit: 'symbol',
    en: ['n', 'N'],
    ru: ['т', 'Т'],
  },
  {
    code: 'KeyM',
    unit: 'symbol',
    en: ['m', 'M'],
    ru: ['ь', 'Ь'],
  },
  {
    code: 'Comma',
    unit: 'splitSymbol',
    en: [',', '<'],
    ru: ['б', 'Б'],
  },
  {
    code: 'Period',
    unit: 'splitSymbol',
    en: ['.', '>'],
    ru: ['ю', 'Ю'],
  },
  {
    code: 'Slash',
    unit: 'splitSymbol',
    en: ['/', '?'],
    ru: ['.', ','],
  },
  {
    code: 'ArrowUp',
    unit: 'spec',
    en: ['Up'],
    ru: ['Up'],
  },
  {
    code: 'ShiftRight',
    unit: 'spec',
    en: ['Shift'],
    ru: ['Shift'],
  },
  {
    code: 'ControlLeft',
    unit: 'spec',
    en: ['Ctrl'],
    ru: ['Ctrl'],
  },
  {
    code: 'MetaLeft',
    unit: 'spec',
    en: ['Win'],
    ru: ['Win'],
  },
  {
    code: 'AltLeft',
    unit: 'spec',
    en: ['Alt'],
    ru: ['Alt'],
  },
  {
    code: 'Space',
    unit: 'spec',
    en: ['Space'],
    ru: ['Space'],
  },
  {
    code: 'AltRight',
    unit: 'spec',
    en: ['Alt'],
    ru: ['Alt'],
  },
  {
    code: 'ControlRight',
    unit: 'spec',
    en: ['Ctrl'],
    ru: ['Ctrl'],
  },
  {
    code: 'ArrowLeft',
    unit: 'spec',
    en: ['Left'],
    ru: ['Left'],
  },
  {
    code: 'ArrowDown',
    unit: 'spec',
    en: ['Down'],
    ru: ['Down'],
  },
  {
    code: 'ArrowRight',
    unit: 'spec',
    en: ['Right'],
    ru: ['Right'],
  },
];

export default dataOfKeys;
